events {}

http {
    upstream items-svc-s13 {
        server items-svc-s13:8101;
    }

    upstream other-svc {
        server other-svc:8102;
    }

    server {
        listen 8080;

        # Маршрут из варианта (нужен для теста)
        location /api/items {
            proxy_pass http://items-svc-s13;
        }

        # По заданию: /api/v1/items
        location /api/v1/items {
            proxy_pass http://items-svc-s13/items;
        }

        # По заданию: /api/v1/other
        location /api/v1/other {
            proxy_pass http://other-svc/other;
        }
    }
}