apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shipments-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.shipments.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audit-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.audit.persistence.size }}
