apiVersion: v2
name: bookings-app
description: Helm chart для сервиса bookings-s13
type: application
version: 0.1.0
appVersion: "1.0"
annotations:
  s13.331.name: bookings-app
  s13.332.name: bookings-app
  s13.431.name: events-app
  s13.432.name: reviews-app
  s13.433.name: products-app
